# Generated by Django 4.0 on 2021-12-23 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('doc_client', models.IntegerField(primary_key=True, serialize=False)),
                ('name_client', models.CharField(max_length=50)),
                ('num_phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('num_invoice', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='hotel_api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id_payment', models.AutoField(primary_key=True, serialize=False)),
                ('method_payment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('num_room', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id_state', models.AutoField(primary_key=True, serialize=False)),
                ('name_state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id_reservation', models.AutoField(primary_key=True, serialize=False)),
                ('stay_days', models.IntegerField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reserv_date', models.DateField()),
                ('invoice_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='hotel_api.invoice')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='hotel_api.payment')),
                ('room_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='hotel_api.room')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='hotel_api.state')),
            ],
        ),
    ]
